version: '3'

services:
  slurm-scheduler:
    build:
      context: .
      args:
        # currently the latest version on EVE
        PYTHON_VERSIONS: "3.8.6 3.9"
    hostname: slurmctl
    stdin_open: true
    tty: true
#    healthcheck:
#      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
#      interval: 10s
#      timeout: 2s
#      retries: 5
#    entrypoint: /bin/bash
    ports:
      - 6820:6820
    volumes:
      # mandatory
      - ./credentials/jwt_hs256.key:/etc/slurm/jwt_hs256.key
      # optional
      - ./volumes/lib:/var/lib/slurmd
      - ./volumes/spool:/var/spool/slurm
      - ./volumes/log:/var/log/slurm
      - ./volumes/db:/var/lib/mysql
